### ISSUE TITLE
[FEAT] 3주차 과제

### ISSUE THREAD

**Issue by wonniiii** [31st-IN-SOPT-iOS-Part/HyowonChoi#4]
## 🛠 Issue

![image](https://user-images.githubusercontent.com/81157265/199906771-8a7eee8d-c772-4433-86c8-2d933e7b612d.png)

## 📋 To-do

- [x] 기본 - FriendList TableView로 구현
- [x] 기본 - ChatLIst CollectionView로 구현
- [x] 기본 - GridPhoto CollectionView로 구현
- [ ] 심화 - UISwipeActionConfiguration 구현
- [ ] 심화 - CollectionView 로직 추가
